# -*- coding: utf-8 -*-
"""testeHTML

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IDa-GqsBsAA--fZmwlCjkKSHlu0Ylyoy

Web Scraper - Pescando dados
"""

import requests
from bs4 import BeautifulSoup
import csv

url = "https://cerradoruralagronegocios.com.br/Publicacao.aspx?id=357087"

response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

tabela = soup.find_all('tbody')

with open('tabela.csv', mode='w', newline='', encoding='utf-8') as arquivo_csv:
    escritor = csv.writer(arquivo_csv)

    for t in tabela:
        linhas = t.find_all('tr')

        for linha in linhas:
            celulas = linha.find_all('td')

            if celulas:
                dados = [celula.get_text(strip=True) for celula in celulas]

                if len(dados) == 7:
                    escritor.writerow(dados)
                else:
                    print(f"Advertência: número de células inconsistente em uma linha - {dados}")

print("Arquivo CSV gerado com sucesso!")